// GitHub-style :shortcode: → emoji, vendored locally (offline by design,
// same as vendor/marked.min.js). Curated set of common shortcodes.

export const EMOJI = {
  // faces
  "grinning": "😀",
  "grin": "😁",
  "smiley": "😃",
  "smile": "😄",
  "laughing": "😆",
  "sweat_smile": "😅",
  "joy": "😂",
  "rofl": "🤣",
  "wink": "😉",
  "blush": "😊",
  "innocent": "😇",
  "heart_eyes": "😍",
  "kissing_heart": "😘",
  "yum": "😋",
  "stuck_out_tongue": "😛",
  "stuck_out_tongue_winking_eye": "😜",
  "stuck_out_tongue_closed_eyes": "😝",
  "drooling_face": "🤤",
  "sunglasses": "😎",
  "nerd_face": "🤓",
  "thinking": "🤔",
  "neutral_face": "😐",
  "expressionless": "😑",
  "no_mouth": "😶",
  "smirk": "😏",
  "unamused": "😒",
  "grimacing": "😬",
  "lying_face": "🤥",
  "relieved": "😌",
  "sleepy": "😪",
  "sleeping": "😴",
  "mask": "😷",
  "sneezing_face": "🤧",
  "dizzy_face": "😵",
  "exploding_head": "🤯",
  "astonished": "😲",
  "flushed": "😳",
  "scream": "😱",
  "fearful": "😨",
  "cold_sweat": "😰",
  "cry": "😢",
  "sob": "😭",
  "disappointed": "😞",
  "sweat": "😓",
  "weary": "😩",
  "tired_face": "😫",
  "angry": "😠",
  "rage": "😡",
  "triumph": "😤",
  "upside_down_face": "🙃",
  "money_mouth_face": "🤑",
  "hugs": "🤗",
  "clown_face": "🤡",
  "cowboy_hat_face": "🤠",
  "partying_face": "🥳",
  "pleading_face": "🥺",
  "hand_over_mouth": "🤭",
  "shushing_face": "🤫",
  "zipper_mouth_face": "🤐",
  "raised_eyebrow": "🤨",
  "monocle_face": "🧐",
  "cold_face": "🥶",
  "hot_face": "🥵",
  "woozy_face": "🥴",
  // gestures
  "+1": "👍",
  "thumbsup": "👍",
  "-1": "👎",
  "thumbsdown": "👎",
  "ok_hand": "👌",
  "v": "✌️",
  "crossed_fingers": "🤞",
  "handshake": "🤝",
  "pray": "🙏",
  "wave": "👋",
  "raised_hand": "✋",
  "hand": "✋",
  "point_up": "☝️",
  "point_down": "👇",
  "point_left": "👈",
  "point_right": "👉",
  "middle_finger": "🖕",
  "fu": "🖕",
  "clap": "👏",
  "muscle": "💪",
  "writing_hand": "✍️",
  "nail_care": "💅",
  "eyes": "👀",
  "ear": "👂",
  "nose": "👃",
  "footprints": "👣",
  "brain": "🧠",
  // hearts and symbols
  "heart": "❤️",
  "orange_heart": "🧡",
  "yellow_heart": "💛",
  "green_heart": "💚",
  "blue_heart": "💙",
  "purple_heart": "💜",
  "black_heart": "🖤",
  "white_heart": "🤍",
  "broken_heart": "💔",
  "kiss": "💋",
  "star": "⭐",
  "sparkles": "✨",
  "boom": "💥",
  "collision": "💥",
  "fire": "🔥",
  "zap": "⚡",
  "100": "💯",
  "check": "✅",
  "white_check_mark": "✅",
  "x": "❌",
  "warning": "⚠️",
  "question": "❓",
  "grey_question": "❔",
  "exclamation": "❗",
  "grey_exclamation": "❕",
  "information_source": "ℹ️",
  "bulb": "💡",
  "zzz": "💤",
  "poop": "💩",
  "hankey": "💩",
  "shit": "💩",
  "ghost": "👻",
  "alien": "👽",
  "robot_face": "🤖",
  "skull": "💀",
  "see_no_evil": "🙈",
  "hear_no_evil": "🙉",
  "speak_no_evil": "🙊",
  // objects and activities
  "rocket": "🚀",
  "tada": "🎉",
  "confetti_ball": "🎊",
  "balloon": "🎈",
  "gift": "🎁",
  "trophy": "🏆",
  "pushpin": "📌",
  "memo": "📝",
  "pencil2": "✏️",
  "book": "📖",
  "books": "📚",
  "mag": "🔍",
  "mag_right": "🔎",
  "lock": "🔒",
  "unlock": "🔓",
  "key": "🔑",
  "hammer": "🔨",
  "wrench": "🔧",
  "gear": "⚙️",
  "link": "🔗",
  "email": "📧",
  "calendar": "📅",
  "hourglass": "⌛",
  "hourglass_flowing_sand": "⏳",
  "moneybag": "💰",
  "dollar": "💵",
  "chart": "📈",
  "briefcase": "💼",
  "computer": "💻",
  "iphone": "📱",
  "camera": "📷",
  "musical_note": "🎵",
  "notes": "🎶",
  "art": "🎨",
  "game_die": "🎲",
  "birthday": "🎂",
  "cake": "🎂",
  "cookie": "🍪",
  "donut": "🍩",
  "pizza": "🍕",
  "hamburger": "🍔",
  "fries": "🍟",
  "taco": "🌮",
  "sushi": "🍣",
  "apple": "🍎",
  "grapes": "🍇",
  "strawberry": "🍓",
  "coffee": "☕",
  "tea": "🍵",
  "beer": "🍺",
  "wine_glass": "🍷",
  // nature, animals, places, transport
  "sunny": "☀️",
  "moon": "🌙",
  "cloud": "☁️",
  "snowflake": "❄️",
  "ocean": "🌊",
  "droplet": "💧",
  "evergreen_tree": "🌲",
  "deciduous_tree": "🌳",
  "palm_tree": "🌴",
  "cactus": "🌵",
  "four_leaf_clover": "🍀",
  "rose": "🌹",
  "sunflower": "🌻",
  "tulip": "🌷",
  "cat": "🐱",
  "dog": "🐶",
  "mouse": "🐭",
  "rabbit": "🐰",
  "fox_face": "🦊",
  "bear": "🐻",
  "panda_face": "🐼",
  "koala": "🐨",
  "tiger": "🐯",
  "lion": "🦁",
  "cow": "🐮",
  "pig": "🐷",
  "frog": "🐸",
  "monkey_face": "🐵",
  "chicken": "🐔",
  "penguin": "🐧",
  "bird": "🐦",
  "fish": "🐟",
  "whale": "🐳",
  "octopus": "🐙",
  "car": "🚗",
  "taxi": "🚕",
  "bus": "🚌",
  "train": "🚂",
  "bike": "🚲",
  "airplane": "✈️",
  "ship": "🚢",
  "anchor": "⚓",
  "house": "🏠",
  "office": "🏢",
  "hospital": "🏥",
  "school": "🏫",
  "checkered_flag": "🏁",
  "triangular_flag_on_post": "🚩",
  // arrows and media
  "arrow_up": "⬆️",
  "arrow_down": "⬇️",
  "arrow_left": "⬅️",
  "arrow_right": "➡️",
  "fast_forward": "⏩",
  "rewind": "⏪",
  "arrow_forward": "▶️",
  "pause_button": "⏸️",
  "stop_button": "⏹️",
  "recycle": "♻️",
  "copyright": "©️",
  "registered": "®️",
  "tm": "™️",
};

const PATTERN = /:([a-zA-Z0-9_+-]+):/g;

// Plain-string replace for previews and fallbacks.
// Unknown :codes: are left untouched.
export function emojify(text) {
  if (!text || text.indexOf(":") === -1) return text;
  return text.replace(PATTERN, (m, name) =>
    Object.prototype.hasOwnProperty.call(EMOJI, name) ? EMOJI[name] : m
  );
}

// Post-render replace over text nodes, so :codes: inside
// fenced code blocks and inline `code` stay literal.
export function emojifyElement(root) {
  const skip = new Set(["CODE", "PRE", "TEXTAREA", "SCRIPT", "STYLE"]);
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes = [];
  let n;
  while ((n = walker.nextNode())) {
    if (!n.nodeValue || n.nodeValue.indexOf(":") === -1) continue;
    let el = n.parentElement;
    let skipNode = false;
    while (el && el !== root) {
      if (skip.has(el.tagName)) {
        skipNode = true;
        break;
      }
      el = el.parentElement;
    }
    if (!skipNode) nodes.push(n);
  }
  for (const node of nodes) {
    node.nodeValue = emojify(node.nodeValue);
  }
}
